### create task with "monthToProcess" argument
POST http://localhost:8080/task/create
Content-Type: application/json

{
    "monthToProcess": 8
}

### create task without "monthToProcess" argument, using current month

POST http://localhost:8080/task/create
Content-Type: application/json

{}

### check task processing result
GET http://localhost:8080/task/check?uuid=
Content-Type: application/json

### check task processing result
GET http://localhost:8080/task/check?uuid=
Content-Type: application/json

### force clean outdated data
GET http://localhost:8080/task/clean
Content-Type: application/json

### Get list of all preloaded persons

GET http://localhost:8080/person
Content-Type: application/json